### ISSUE TITLE
Library can't process cloudtrail SNS validation messages

### ISSUE THREAD

**Issue by nick-wellinghoff-sp** [aws/aws-cloudtrail-processing-library#9]
When a cloudtrail is setup, it not only sends notification messages to the SQS queue but also validation messages like this one. 

{
  "Type" : "Notification",
  "MessageId" : "e8ec0cb4-e3cc-5533-8e72-5f0cb6428101",
  "TopicArn" : "arn:aws:sns:us-east-2:69443:ionAudit",
  "Message" : "CloudTrail validation message.",
  "Timestamp" : "2018-07-05T17:20:14.111Z",
  "SignatureVersion" : "1",
  "Signature" : "63Bsy+S5euNtWQx3eebA9wFZN+mLJbw8cD3ArhI+d8GzVJ2DDtqklDR5ktKpqrxtcyl3fU6QxGuy7BlVYCO0HHn3oASMAtYDc5UxQa0YMYomhE2vMsAyG11fksqJ/Pgr0jd/DpBT01Ue8cvW15/JuKzXj50pZLWP1oKcJ4S2qpn02tFwNMr6CwqP0/DVZs5Td/xT6n9LMm4+IoPGT2L1rIwCKOe/C2l3MKGkPUPgNnT+dADN9jxOevsaPc9aXJueZQLGkJOtlNJKvnYYLcQB+p4A==",
  "SigningCertURL" : "https://sns.us-east-2.amazonaws.com/Sd002d285f9598aa1d9b.pem",
  "UnsubscribeURL" : "https://sns.us-east-2.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-2:3:Sudit:bc854278-4a1d-413d-8a78-1206c8e4fe57"
}

The lib throws an exception when trying to parse these messages.

2018-07-05 16:58:23,765 ERROR pool-1-thread-1 cloudtrail.processinglibrary.impl.DefaultExceptionHandler:32 - Failed to parse sqs message.
com.amazonaws.services.cloudtrail.processinglibrary.exceptions.ProcessingLibraryException: Failed to parse sqs message.
        at com.amazonaws.services.cloudtrail.processinglibrary.utils.LibraryUtils.handleException(LibraryUtils.java:170)
        at com.amazonaws.services.cloudtrail.processinglibrary.manager.SqsManager.parseMessage(SqsManager.java:165)
        at com.amazonaws.services.cloudtrail.processinglibrary.reader.EventReader.getSources(EventReader.java:113)
        at com.amazonaws.services.cloudtrail.processinglibrary.AWSCloudTrailProcessingExecutor$ScheduledJob.run(AWSCloudTrailProcessingExecutor.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: SourceSerializerChain expect JSON content
        at com.amazonaws.services.cloudtrail.processinglibrary.serializer.SourceSerializerChain.getCloudTrailSource(SourceSerializerChain.java:98)
        at com.amazonaws.services.cloudtrail.processinglibrary.serializer.SourceSerializerChain.getSource(SourceSerializerChain.java:73)
        at com.amazonaws.services.cloudtrail.processinglibrary.manager.SqsManager.parseMessage(SqsManager.java:158)
        ... 9 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'CloudTrail': was expecting ('true', 'false' or 'null')
 at [Source: (String)"CloudTrail validation message."; line: 1, column: 11]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:673)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1889)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4030)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2539)
        at com.amazonaws.services.cloudtrail.processinglibrary.utils.SNSMessageBodyExtractor.getMessageBody(SNSMessageBodyExtractor.java:37)
        at com.amazonaws.services.cloudtrail.processinglibrary.serializer.CloudTrailSourceSerializer.getSource(CloudTrailSourceSerializer.java:59)
        at com.amazonaws.services.cloudtrail.processinglibrary.serializer.SourceSerializerChain.getCloudTrailSource(SourceSerializerChain.java:96)

Seems like the lib should toss these messages. Or is there something I can setup so these validation messages don't go to my queue?

**Comment by jeffmcr** [comment]
This issue has been resolved in release 1.1.3.

Support was added for automatically deleting the initial SNS validation message sent whenever an SNS topic for a trail is configured or updated. In previous releases, these messages had to be manually deleted.
